# Generated by Django 5.2.1 on 2025-07-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='neg_text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pos_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='no comment'),
            preserve_default=False,
        ),
    ]
